### ISSUE TITLE
TypeError: CleanWebpackPlugin is not a function

### ISSUE THREAD

**Issue by step271828** [PacktPublishing/Hands-on-Full-Stack-Web-Development-with-GraphQL-and-React#1]
Chapter 1 webpack.client.config.js  throws the above error. Line 3 needs to be changed to: 

const { CleanWebpackPlugin } = require('clean-webpack-plugin');

**Comment by frannav** [comment]
Thank u!

**Comment by Sebi55** [comment]
Are you sure you are using the `package.json` provided with the project?

The `clean-webpack-plugin` in the latest version requires you to do that but not the version specified in the `package.json` which is an older version.

Please compare the documentation of the plugin.
Version 2.0.1 (used): https://github.com/johnagan/clean-webpack-plugin/tree/v2.0.1
Latest: https://github.com/johnagan/clean-webpack-plugin

If there is a step in the book requiring you to update the packages which leads to this problem please inform me.

**Comment by alescarzello** [comment]
The book don't specify the version of clean-webpack-plugin you're installing. clean-webpack-plugin@2.0.1 should be added to the npm command line given in page 15 of the book.

Sorry for my english.

Thanks!

**Comment by gaurav-packt** [comment]
Thanks for the feedback.
