### ISSUE TITLE
__requireContext is not defined

### ISSUE THREAD

**Issue by AntonioSilvaDev** [PacktPublishing/Hands-on-Full-Stack-Web-Development-with-GraphQL-and-React#2]
Getting this error, Chapter 3, when it's looking for the process.env.NODE_ENV before the require.context is called in the models index.js file. I know you say "Make sure that you set the NODE_ENV variable to development; otherwise, this won't work.", just not sure where you are setting this in the documentation.  Getting by with:
`import Sequelize from 'sequelize';

const env = process.env.NODE_ENV || 'development';

if (env === 'development') {
  require('babel-plugin-require-context-hook/register')();
}

export default (sequelize) => {
  let db = {};

  const context = require.context('.', true, /^\.\/(?!index\.js).*\.js$/, 'sync');

  context
    .keys()
    .map(context)
    .forEach((module) => {
      const model = module(sequelize, Sequelize);
      db[model.name] = model;
    });

  Object.keys(db).forEach((modelName) => {
    if (db[modelName].associate) {
      db[modelName].associate(db);
    }
  });

  return db;
};`

**Comment by trannhutle** [comment]
I have got the same issue mate!

**Comment by Sebi55** [comment]
Sorry I need to ask again but you are asking where the `NODE_ENV ` variable/property comes from?

If so you need set it the `NODE_ENV` variable not inside your application as it is an environment variable. It is set on machine / process level. This why you access it via `process.env.[VARIABLE_NAME]`.
The `process` object is the current Node.js process including important information including environment variables specified in the `env` property of the `process` object.

You should read up on environment variables a bit. Here is a good link: [https://superuser.com/questions/284342/what-are-path-and-other-environment-variables-and-how-can-i-set-or-use-them](https://superuser.com/questions/284342/what-are-path-and-other-environment-variables-and-how-can-i-set-or-use-them)
Please have a look at how to set environment variabels correctly. It highly depends on the operating system your are using as explained in the link.

This is important for nearly all programming languages and not directly part of the book as it is something that is assumed to be known.

**Comment by gaurav-packt** [comment]
Closing the issue with respect to the feedback shared by the author

**Comment by gaurav-packt** [comment]
Hello, the issue can be resolved by changing the version as: clean-webpack-plugin@2.0.1; on page 15 of the book.

Thanks @Sebi55 for the feedback.

**Comment by antrannguyen** [comment]
Hello, 

I also have that issue and cannot fix event I have updated the clean-webpack-plugin to 2.0.1. Please advice
