### ISSUE TITLE
__requireContext is not defined

### ISSUE THREAD

**Issue by antrannguyen** [PacktPublishing/Hands-on-Full-Stack-Web-Development-with-GraphQL-and-React#70]
Getting this error, Chapter 3, when it's looking for the process.env.NODE_ENV before the require.context is called in the models index.js file. I know you say "Make sure that you set the NODE_ENV variable to development; otherwise, this won't work.", just not sure where you are setting this in the documentation. Getting by with:
`import Sequelize from 'sequelize';

if (process.env.NODE_ENV === 'development') {
require('babel-plugin-require-context-hook/register')();
}

export default (sequelize) => {
let db = {};

const context = require.context('.', true, /^./(?!index.js).*.js$/, 'sync');

context
.keys()
.map(context)
.forEach((module) => {
const model = module(sequelize, Sequelize);
db[model.name] = model;
});

Object.keys(db).forEach((modelName) => {
if (db[modelName].associate) {
db[modelName].associate(db);
}
});

return db;
};

**Comment by antrannguyen** [comment]
I also have that issue and cannot fix event I have updated the clean-webpack-plugin to 2.0.1. Please advice

**Comment by Sebi55** [comment]
Can you provide your package.json file?
Furthermore did you install or remove the old package version and install the correct version?

**Comment by antrannguyen** [comment]
Hello Sebi55, thank you for your reply, here is my package.json file
`"scripts": {
		"client": "webpack-dev-server --devtool inline-source-map --hot --config webpack.client.config.js",
		"client:build": "webpack --config webpack.client.build.config.js",
		"server": "nodemon --exec babel-node --plugins require-context-hook  --watch src/server src/server/index.js",
		"stats": "webpack --profile --json --config webpack.client.build.config.js > stats.json",
		"analyze": "webpack-bundle-analyzer stats.json",
		"test": "echo \"Error: no test specified\" && exit 1"
	},
	"author": "",
	"license": "ISC",
	"dependencies": {
		"apollo-server": "^2.19.1",
		"apollo-server-express": "^2.19.0",
		"compression": "^1.7.4",
		"cors": "^2.8.5",
		"express": "^4.17.1",
		"graphql": "^15.4.0",
		"graphql-tools": "^7.0.2",
		"helmet": "^4.2.0",
		"mysql2": "^2.2.5",
		"nodemon": "^2.0.6",
		"react": "^16.6.3",
		"react-dom": "^16.6.3",
		"react-helmet": "^5.2.0",
		"require-context": "^1.1.0",
		"sequelize": "^6.3.5",
		"winston": "^3.3.3"
	},
	"devDependencies": {
		"@babel/core": "^7.1.6",
		"@babel/node": "^7.12.6",
		"@babel/plugin-proposal-class-properties": "^7.1.0",
		"@babel/plugin-proposal-decorators": "^7.1.6",
		"@babel/plugin-proposal-export-namespace-from": "^7.0.0",
		"@babel/plugin-proposal-function-sent": "^7.1.0",
		"@babel/plugin-proposal-numeric-separator": "^7.0.0",
		"@babel/plugin-proposal-throw-expressions": "^7.0.0",
		"@babel/preset-env": "^7.1.6",
		"@babel/preset-react": "^7.0.0",
		"babel-eslint": "^10.0.1",
		"babel-loader": "^8.0.4",
		"babel-plugin-require-context-hook": "^1.0.0",
		"clean-webpack-plugin": "^2.0.1",
		"css-loader": "^1.0.1",
		"eslint": "^5.3.0",
		"eslint-config-airbnb": "^17.1.0",
		"eslint-plugin-import": "^2.14.0",
		"eslint-plugin-jsx-a11y": "^6.1.1",
		"eslint-plugin-react": "^7.11.0",
		"file-loader": "^2.0.0",
		"html-webpack-plugin": "^3.2.0",
		"mini-css-extract-plugin": "^0.4.5",
		"style-loader": "^0.23.1",
		"url-loader": "^1.1.2",
		"webpack": "^4.26.1",
		"webpack-bundle-analyzer": "^3.0.3",
		"webpack-cli": "^3.1.2",
		"webpack-dev-server": "^3.1.10"
	}`

**Comment by antrannguyen** [comment]
`"scripts": {
		"client": "webpack-dev-server --devtool inline-source-map --hot --config webpack.client.config.js",
		"client:build": "webpack --config webpack.client.build.config.js",
		"server": "nodemon --exec babel-node --plugins require-context-hook  --watch src/server src/server/index.js",
		"stats": "webpack --profile --json --config webpack.client.build.config.js > stats.json",
		"analyze": "webpack-bundle-analyzer stats.json",
		"test": "echo \"Error: no test specified\" && exit 1"
	},
	"author": "",
	"license": "ISC",
	"dependencies": {
		"apollo-server": "^2.19.1",
		"apollo-server-express": "^2.19.0",
		"compression": "^1.7.4",
		"cors": "^2.8.5",
		"express": "^4.17.1",
		"graphql": "^15.4.0",
		"graphql-tools": "^7.0.2",
		"helmet": "^4.2.0",
		"mysql2": "^2.2.5",
		"nodemon": "^2.0.6",
		"react": "^16.6.3",
		"react-dom": "^16.6.3",
		"react-helmet": "^5.2.0",
		"require-context": "^1.1.0",
		"sequelize": "^6.3.5",
		"winston": "^3.3.3"
	},
	"devDependencies": {
		"@babel/core": "^7.1.6",
		"@babel/node": "^7.12.6",
		"@babel/plugin-proposal-class-properties": "^7.1.0",
		"@babel/plugin-proposal-decorators": "^7.1.6",
		"@babel/plugin-proposal-export-namespace-from": "^7.0.0",
		"@babel/plugin-proposal-function-sent": "^7.1.0",
		"@babel/plugin-proposal-numeric-separator": "^7.0.0",
		"@babel/plugin-proposal-throw-expressions": "^7.0.0",
		"@babel/preset-env": "^7.1.6",
		"@babel/preset-react": "^7.0.0",
		"babel-eslint": "^10.0.1",
		"babel-loader": "^8.0.4",
		"babel-plugin-require-context-hook": "^1.0.0",
		"clean-webpack-plugin": "^2.0.1",
		"css-loader": "^1.0.1",
		"eslint": "^5.3.0",
		"eslint-config-airbnb": "^17.1.0",
		"eslint-plugin-import": "^2.14.0",
		"eslint-plugin-jsx-a11y": "^6.1.1",
		"eslint-plugin-react": "^7.11.0",
		"file-loader": "^2.0.0",
		"html-webpack-plugin": "^3.2.0",
		"mini-css-extract-plugin": "^0.4.5",
		"style-loader": "^0.23.1",
		"url-loader": "^1.1.2",
		"webpack": "^4.26.1",
		"webpack-bundle-analyzer": "^3.0.3",
		"webpack-cli": "^3.1.2",
		"webpack-dev-server": "^3.1.10"
	}`

**Comment by Sebi55** [comment]
Please try using the exact version and then run npm install again.

**Comment by antrannguyen** [comment]
i tried to run server after import db in the index.js server side, and it have an error when running the require.context: 
![Screenshot 2020-12-29 at 14 20 45](https://user-images.githubusercontent.com/52281429/103283395-23154d80-49e1-11eb-96be-1457e705fc2e.png)

**Comment by Sebi55** [comment]
I tested it myself. I think that you are still missing to set the NODE_ENV properly.
Maybe you should have a look at what the other issue suggested:
```
const env = process.env.NODE_ENV || 'development';

if (env === 'development') {
```
This will ensure that the `env` variable is set.
For me it is working after setting my environment variable on my machine. You should follow the closed issue.

**Comment by antrannguyen** [comment]
I fixed it, thank you @Sebi55 and happy new year !!!

**Comment by Sebi55** [comment]
Absolutely no problem 👍 
If the solution was another one than recommended by me please share the information for the other readers.
